readline fix and exit
JackBoreczky/4H-makerspace pull request #21
Opened 2021-03-23 23:20 UTC by JackBoreczky

Add an import for pyreadline if readline errors (happens on windows). Also add another way to exit the game.

2021-03-24 22:40 UTC, bitbloxhub commented on eat_shovel.py
> +        "exit": exit_game
add trailing comma

2021-03-24 22:42 UTC, bitbloxhub requested changes
nice! but see below

2021-03-24 22:42 UTC, bitbloxhub commented on eat_shovel.py
> +        "exit": exit_game
add trailing comma

2021-03-25 00:54 UTC, JackBoreczky commented on eat_shovel.py
> +        "exit": exit_game
resolved!

2021-03-25 00:58 UTC, bitbloxhub approved these changes
ok

2021-03-25 00:59 UTC, merged

2021-03-25 00:59 UTC, bitbloxhub commented
do not delete branch